<template><div><h1 id="api" tabindex="-1"><a class="header-anchor" href="#api"><span>API</span></a></h1>
<h2 id="method-list" tabindex="-1"><a class="header-anchor" href="#method-list"><span>Method List</span></a></h2>
<p>All Odoo current API methods.
<br>
The name of the methods can be used to implement custom queries.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token comment">// packages/theme/middleware.config.js</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">OdooApiMethods</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function">getCategory</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlGetCategoryParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CategoryResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">getProductTemplatesList</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlGetProductParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ProductResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">getProductTemplate</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlGetProductTemplateParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>SingleProductResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">getRealProduct</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlGetProductVariantParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ProductVariantResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">updateAccount</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlUpdateAccountParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">signUpUser</span><span class="token punctuation">(</span>params<span class="token operator">:</span> Partner<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>RegisterResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">logInUser</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlLoginParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>LoginResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">logOutUser</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>Partner<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">loadUser</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>LoadUserResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">sendResetPassword</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlSendResetPasswordParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>DefaultGraphQlMutationResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">changePassword</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlResetPasswordParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>DefaultGraphQlMutationResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">cartAddMultipleItems</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlAddMultipleProductsParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>cartAddMultipleItemsResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">cartRemoveMultipleItems</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlRemoveMultipleProductsParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>cartRemoveMultipleItemsResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">cartLoad</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CartLoadResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">cartAddItem</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlCartAddItemParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CartAddItemResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">cartRemoveItem</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlCartRemoveItemParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CartRemoveItemResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">cartUpdateItemQty</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlCartUpdateItemQtyParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">wishlistLoad</span> <span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>WishlistLoadResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">wishlistAddItem</span> <span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlWishlistAddItemParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>WishlistAddItemResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">wishlistRemoveItem</span> <span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlWishlistRemoveItemParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>WishlistRemoveItemResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">getCountries</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CountriesResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">getCountryStates</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlGetCountryParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>CountryStatesResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">shippingAddAdress</span><span class="token punctuation">(</span>shippingAdress<span class="token operator">:</span> GraphQlAddAddressParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ShippingAddAddresResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">shippingUpdateAddress</span><span class="token punctuation">(</span>shippingAdress<span class="token operator">:</span> GraphQlUpdateAddressParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ShippingUpdateAddressResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">shippingGetDeliveryMethods</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ShippingGetDeliveryMethodsResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">shippingGetAddress</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>ShippingGetAddresessResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">billingAddAddress</span><span class="token punctuation">(</span>shippingAdress<span class="token operator">:</span> GraphQlAddAddressParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>BillingAddAddresResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">billingUpdateAddress</span><span class="token punctuation">(</span>shippingAdress<span class="token operator">:</span> GraphQlUpdateAddressParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>BillingUpdateAddressResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">billingGetAddress</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>BillingGetAddressResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">deleteAddress</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlDeleteAddressParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span><span class="token keyword">void</span><span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">paymentLoadProviders</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>PaymentLoadProvidersResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">paymentMakeExternal</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlMakePaymentParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>PaymentMakeExternalResult<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">paymentConfirmation</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">subscribeNewsLetter</span><span class="token punctuation">(</span>customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">ordersGet</span><span class="token punctuation">(</span>params<span class="token operator">:</span> GraphQlOrdersParams<span class="token punctuation">,</span> customQuery<span class="token operator">?</span><span class="token operator">:</span> CustomQuery<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>FetchResult<span class="token operator">&lt;</span>OrdersResponse<span class="token operator">>></span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


