module.exports = {
  purge: [],
  important: true,
  prefix: 'tw-',
  theme: {
    extend: {
      fontSize: {
        'sf-xs': 'var(--font-size--xs)',
        'sf-sm': 'var(--font-size--sm)',
        'sf-base': 'var(--font-size--base)',
        'sf-lg': 'var(--font-size--lg)'
      },
      fontWeight: {
        'sf-light': 'var(--font-weight--light)',
        'sf-normal': 'var(--font-weight--normal)',
        'sf-medium': 'var(--font-weight--medium)',
        'sf-semibold': 'var(--font-weight--semibold)',
        'sf-bold': 'var(--font-weight--bold)'
      },
      colors: {
        'sf-c-black': 'var(--c-black)',
        'sf-c-black-base': 'var(--c-black-base)',
        'sf-c-black-lighten': 'var(--c-black-lighten)',
        'sf-c-black-darken': 'var( --c-black-darken)',
        'sf-c-white': 'var(--c-white)',
        'sf-c-body': 'var(--c-body)',
        'sf-c-text': 'var(--c-text)',
        'sf-c-text-muted': 'var(--c-text-muted)',
        'sf-c-text-disabled': 'var(--c-text-disabled)',
        'sf-c-link': 'var(--c-link)',
        'sf-c-link-hover': 'var(--c-link-hover)',
        'sf-c-primary': 'var(--c-primary)',
        'sf-c-primary-base': 'var(--c-primary-base)',
        'sf-c-primary-lighten': 'var(--c-primary-lighten)',
        'sf-c-primary-darken': 'var(--c-primary-darken)',
        'sf-c-primary-variant': 'var(--c-primary-variant)',
        'sf-c-on-primary': 'var(--c-on-primary)',
        'sf-c-secondary': 'var( --c-secondary)',
        'sf-c-secondary-base': 'var(--c-secondary-base)',
        'sf-c-secondary-lighten': 'var(--c-secondary-lighten)',
        'sf-c-secondary-darken': 'var(--c-secondary-darken)',
        'sf-c-secondary-variant': 'var(--c-secondary-variant)',
        'sf-c-on-secondary': 'var(--c-on-secondary)',
        'sf-c-light': 'var(--c-light)',
        'sf-c-light-base': 'var(--c-light-base)',
        'sf-c-light-lighten': 'var(--c-light-lighten)',
        'sf-c-light-darken': 'var(--c-light-darken)',
        'sf-c-light-variant': 'var(--c-light-variant)',
        'sf-c-on-light': 'var(--c-on-light)',
        'sf-c-gray': 'var(--c-gray)',
        'sf-c-gray-base': 'var(--c-gray-base)',
        'sf-c-gray-lighten': 'var(--c-gray-lighten)',
        'sf-c-gray-darken': 'var(--c-gray-darken)',
        'sf-c-gray-variant': 'var(--c-gray-variant)',
        'sf-c-on-gray': 'var(--c-on-gray)',
        'sf-c-dark': 'var(--c-dark)',
        'sf-c-dark-base': 'var(--c-dark-base)',
        'sf-c-dark-lighten': 'var(--c-dark-lighten)',
        'sf-c-dark-darken': 'var(--c-dark-darken)',
        'sf-c-dark-variant': 'var(--c-dark-variant)',
        'sf-c-on-dark': 'var(--c-on-dark)',
        'sf-c-info': 'var(--c-info)',
        'sf-c-info-base': 'var(--c-info-base)',
        'sf-c-info-lighten': 'var(--c-info-lighten)',
        'sf-c-info-darken': 'var(--c-info-darken)',
        'sf-c-info-variant': 'var(--c-info-variant)',
        'sf-c-on-info': 'var(--c-on-info)',
        'sf-c-success': 'var(--c-success)',
        'sf-c-success-base': 'var(--c-success-base)',
        'sf-c-success-lighten': 'var(--c-success-lighten)',
        'sf-c-success-darken': 'var(--c-success-darken)',
        'sf-c-success-variant': 'var(--c-success-variant)',
        'sf-c-on-success': 'var(--c-on-success)',
        'sf-c-warning': 'var(--c-warning)',
        'sf-c-warning-base': 'var(--c-warning-base)',
        'sf-c-warning-lighten': 'var(--c-warning-lighten)',
        'sf-c-warning-darken': 'var(--c-warning-darken)',
        'sf-c-warning-variant': 'var(--c-warning-variant)',
        'sf-c-on-warning': 'var(--c-on-warning)',
        'sf-c-danger': 'var(--c-danger)',
        'sf-c-danger-base': 'var(--c-danger-base)',
        'sf-c-danger-lighten': 'var(--c-danger-lighten)',
        'sf-c-danger-darken': 'var(--c-danger-darken)',
        'sf-c-danger-variant': 'var(--c-danger-variant)',
        'sf-c-on-danger': 'var(--c-on-danger)'
      },
      spacing: {
        'sf-2xs': 'var(--spacer-2xs)',
        'sf-xs': 'var( --spacer-xs)',
        'sf-sm': 'var(--spacer-sm)',
        'sf-base': 'var(--spacer-base)',
        'sf-lg': 'var(--spacer-lg)',
        'sf-xl': 'var(--spacer-xl)',
        'sf-2xl': 'var(--spacer-2xl)',
        'sf-3xl': 'var(--spacer-3xl)'
      },
      fontFamily: {
        'sf-primary': 'var(--font-family--primary)',
        'sf-secondary': 'var(--font-family--secondary)'
      }
    },
    variants: {},
    plugins: []
  }
};
