
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CodeEmbed': typeof import("../components/content/CodeEmbed.vue")['default']
    'Card': typeof import("../node_modules/sf-docs-base/components/content/Card.vue")['default']
    'CodeGroup': typeof import("../node_modules/sf-docs-base/components/content/CodeGroup.vue")['default']
    'Container': typeof import("../node_modules/sf-docs-base/components/content/Container.vue")['default']
    'Danger': typeof import("../node_modules/sf-docs-base/components/content/Danger.vue")['default']
    'DocsArrowLink': typeof import("../node_modules/sf-docs-base/components/content/DocsArrowLink.vue")['default']
    'DocsButton': typeof import("../node_modules/sf-docs-base/components/content/DocsButton.vue")['default']
    'Grid': typeof import("../node_modules/sf-docs-base/components/content/Grid.vue")['default']
    'Info': typeof import("../node_modules/sf-docs-base/components/content/Info.vue")['default']
    'IntegrationList': typeof import("../node_modules/sf-docs-base/components/content/IntegrationList.vue")['default']
    'List': typeof import("../node_modules/sf-docs-base/components/content/List.vue")['default']
    'Partial': typeof import("../node_modules/sf-docs-base/components/content/Partial.vue")['default']
    'ReadMore': typeof import("../node_modules/sf-docs-base/components/content/ReadMore.vue")['default']
    'ReferenceExample': typeof import("../node_modules/sf-docs-base/components/content/ReferenceExample.vue")['default']
    'ReferencePropertyHeading': typeof import("../node_modules/sf-docs-base/components/content/ReferencePropertyHeading.vue")['default']
    'ReferenceToggle': typeof import("../node_modules/sf-docs-base/components/content/ReferenceToggle.vue")['default']
    'RemoteCode': typeof import("../node_modules/sf-docs-base/components/content/RemoteCode.vue")['default']
    'Steps': typeof import("../node_modules/sf-docs-base/components/content/Steps.vue")['default']
    'Subheader': typeof import("../node_modules/sf-docs-base/components/content/Subheader.vue")['default']
    'SwaggerDocs': typeof import("../node_modules/sf-docs-base/components/content/SwaggerDocs.vue")['default']
    'Tabs': typeof import("../node_modules/sf-docs-base/components/content/Tabs.vue")['default']
    'Tip': typeof import("../node_modules/sf-docs-base/components/content/Tip.vue")['default']
    'Warning': typeof import("../node_modules/sf-docs-base/components/content/Warning.vue")['default']
    'ContainerGradient': typeof import("../node_modules/sf-docs-base/components/content/container/ContainerGradient.vue")['default']
    'ContainerTab': typeof import("../node_modules/sf-docs-base/components/content/container/ContainerTab.vue")['default']
    'ProseA': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseA.vue")['default']
    'ProseCode': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseCode.vue")['default']
    'ProseH2': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH4.vue")['default']
    'IconAlgolia': typeof import("../node_modules/sf-docs-base/components/global/icon/IconAlgolia.vue")['default']
    'IconAmplience': typeof import("../node_modules/sf-docs-base/components/global/icon/IconAmplience.vue")['default']
    'IconBazaarvoice': typeof import("../node_modules/sf-docs-base/components/global/icon/IconBazaarvoice.vue")['default']
    'IconBloomreach': typeof import("../node_modules/sf-docs-base/components/global/icon/IconBloomreach.vue")['default']
    'IconCheckout': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCheckout.vue")['default']
    'IconCommercetools': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCommercetools.vue")['default']
    'IconConstructor': typeof import("../node_modules/sf-docs-base/components/global/icon/IconConstructor.vue")['default']
    'IconContentstack': typeof import("../node_modules/sf-docs-base/components/global/icon/IconContentstack.vue")['default']
    'IconCoveo': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCoveo.vue")['default']
    'IconLexasCMS': typeof import("../node_modules/sf-docs-base/components/global/icon/IconLexasCMS.vue")['default']
    'IconMollie': typeof import("../node_modules/sf-docs-base/components/global/icon/IconMollie.vue")['default']
    'IconOdoo': typeof import("../node_modules/sf-docs-base/components/global/icon/IconOdoo.vue")['default']
    'IconPlentyMarkets': typeof import("../node_modules/sf-docs-base/components/global/icon/IconPlentyMarkets.vue")['default']
    'IconPrestashop': typeof import("../node_modules/sf-docs-base/components/global/icon/IconPrestashop.vue")['default']
    'IconSAP': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSAP.vue")['default']
    'IconSanity': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSanity.vue")['default']
    'IconSpree': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSpree.vue")['default']
    'IconStorefrontUi': typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUi.vue")['default']
    'IconStorefrontUiFull': typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUiFull.vue")['default']
    'IconSylius': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSylius.vue")['default']
    'IconVsf': typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsf.vue")['default']
    'IconVsfFull': typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsfFull.vue")['default']
    'AppEdit': typeof import("../node_modules/sf-docs-base/components/app/AppEdit.vue")['default']
    'AppFooter': typeof import("../node_modules/sf-docs-base/components/app/AppFooter.vue")['default']
    'AppHeader': typeof import("../node_modules/sf-docs-base/components/app/AppHeader.vue")['default']
    'AppLayout': typeof import("../node_modules/sf-docs-base/components/app/AppLayout.vue")['default']
    'AppLayoutDefault': typeof import("../node_modules/sf-docs-base/components/app/AppLayoutDefault.vue")['default']
    'AppLayoutFullscreen': typeof import("../node_modules/sf-docs-base/components/app/AppLayoutFullscreen.vue")['default']
    'AppSearch': typeof import("../node_modules/sf-docs-base/components/app/AppSearch.vue")['default']
    'AppSidebar': typeof import("../node_modules/sf-docs-base/components/app/AppSidebar.vue")['default']
    'AppSidebarBottom': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarBottom.vue")['default']
    'AppSidebarTop': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTop.vue")['default']
    'AppSidebarTree': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTree.vue")['default']
    'AppTableOfContents': typeof import("../node_modules/sf-docs-base/components/app/AppTableOfContents.vue")['default']
    'AppTag': typeof import("../node_modules/sf-docs-base/components/app/AppTag.vue")['default']
    'AppVersionSelector': typeof import("../node_modules/sf-docs-base/components/app/AppVersionSelector.vue")['default']
    'ReferenceCode': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceCode.vue")['default']
    'ReferenceFunction': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceFunction.vue")['default']
    'ReferenceInterface': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceInterface.vue")['default']
    'ReferenceItem': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceItem.vue")['default']
    'ReferenceProperties': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperties.vue")['default']
    'ReferenceProperty': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperty.vue")['default']
    'ReferenceReferences': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceReferences.vue")['default']
    'ReferenceVariable': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceVariable.vue")['default']
    'SfDropdown': typeof import("../node_modules/sf-docs-base/components/sf/SfDropdown.vue")['default']
    'ContentDoc': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'DocumentDrivenEmpty': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'Markdown': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseCodeInline': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'ProsePre': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseEm': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH5': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProseScript': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'MDC': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
    'MDCRenderer': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
    'MDCSlot': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCodeEmbed': typeof import("../components/content/CodeEmbed.vue")['default']
    'LazyCard': typeof import("../node_modules/sf-docs-base/components/content/Card.vue")['default']
    'LazyCodeGroup': typeof import("../node_modules/sf-docs-base/components/content/CodeGroup.vue")['default']
    'LazyContainer': typeof import("../node_modules/sf-docs-base/components/content/Container.vue")['default']
    'LazyDanger': typeof import("../node_modules/sf-docs-base/components/content/Danger.vue")['default']
    'LazyDocsArrowLink': typeof import("../node_modules/sf-docs-base/components/content/DocsArrowLink.vue")['default']
    'LazyDocsButton': typeof import("../node_modules/sf-docs-base/components/content/DocsButton.vue")['default']
    'LazyGrid': typeof import("../node_modules/sf-docs-base/components/content/Grid.vue")['default']
    'LazyInfo': typeof import("../node_modules/sf-docs-base/components/content/Info.vue")['default']
    'LazyIntegrationList': typeof import("../node_modules/sf-docs-base/components/content/IntegrationList.vue")['default']
    'LazyList': typeof import("../node_modules/sf-docs-base/components/content/List.vue")['default']
    'LazyPartial': typeof import("../node_modules/sf-docs-base/components/content/Partial.vue")['default']
    'LazyReadMore': typeof import("../node_modules/sf-docs-base/components/content/ReadMore.vue")['default']
    'LazyReferenceExample': typeof import("../node_modules/sf-docs-base/components/content/ReferenceExample.vue")['default']
    'LazyReferencePropertyHeading': typeof import("../node_modules/sf-docs-base/components/content/ReferencePropertyHeading.vue")['default']
    'LazyReferenceToggle': typeof import("../node_modules/sf-docs-base/components/content/ReferenceToggle.vue")['default']
    'LazyRemoteCode': typeof import("../node_modules/sf-docs-base/components/content/RemoteCode.vue")['default']
    'LazySteps': typeof import("../node_modules/sf-docs-base/components/content/Steps.vue")['default']
    'LazySubheader': typeof import("../node_modules/sf-docs-base/components/content/Subheader.vue")['default']
    'LazySwaggerDocs': typeof import("../node_modules/sf-docs-base/components/content/SwaggerDocs.vue")['default']
    'LazyTabs': typeof import("../node_modules/sf-docs-base/components/content/Tabs.vue")['default']
    'LazyTip': typeof import("../node_modules/sf-docs-base/components/content/Tip.vue")['default']
    'LazyWarning': typeof import("../node_modules/sf-docs-base/components/content/Warning.vue")['default']
    'LazyContainerGradient': typeof import("../node_modules/sf-docs-base/components/content/container/ContainerGradient.vue")['default']
    'LazyContainerTab': typeof import("../node_modules/sf-docs-base/components/content/container/ContainerTab.vue")['default']
    'LazyProseA': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseA.vue")['default']
    'LazyProseCode': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseCode.vue")['default']
    'LazyProseH2': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH4.vue")['default']
    'LazyIconAlgolia': typeof import("../node_modules/sf-docs-base/components/global/icon/IconAlgolia.vue")['default']
    'LazyIconAmplience': typeof import("../node_modules/sf-docs-base/components/global/icon/IconAmplience.vue")['default']
    'LazyIconBazaarvoice': typeof import("../node_modules/sf-docs-base/components/global/icon/IconBazaarvoice.vue")['default']
    'LazyIconBloomreach': typeof import("../node_modules/sf-docs-base/components/global/icon/IconBloomreach.vue")['default']
    'LazyIconCheckout': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCheckout.vue")['default']
    'LazyIconCommercetools': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCommercetools.vue")['default']
    'LazyIconConstructor': typeof import("../node_modules/sf-docs-base/components/global/icon/IconConstructor.vue")['default']
    'LazyIconContentstack': typeof import("../node_modules/sf-docs-base/components/global/icon/IconContentstack.vue")['default']
    'LazyIconCoveo': typeof import("../node_modules/sf-docs-base/components/global/icon/IconCoveo.vue")['default']
    'LazyIconLexasCMS': typeof import("../node_modules/sf-docs-base/components/global/icon/IconLexasCMS.vue")['default']
    'LazyIconMollie': typeof import("../node_modules/sf-docs-base/components/global/icon/IconMollie.vue")['default']
    'LazyIconOdoo': typeof import("../node_modules/sf-docs-base/components/global/icon/IconOdoo.vue")['default']
    'LazyIconPlentyMarkets': typeof import("../node_modules/sf-docs-base/components/global/icon/IconPlentyMarkets.vue")['default']
    'LazyIconPrestashop': typeof import("../node_modules/sf-docs-base/components/global/icon/IconPrestashop.vue")['default']
    'LazyIconSAP': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSAP.vue")['default']
    'LazyIconSanity': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSanity.vue")['default']
    'LazyIconSpree': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSpree.vue")['default']
    'LazyIconStorefrontUi': typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUi.vue")['default']
    'LazyIconStorefrontUiFull': typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUiFull.vue")['default']
    'LazyIconSylius': typeof import("../node_modules/sf-docs-base/components/global/icon/IconSylius.vue")['default']
    'LazyIconVsf': typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsf.vue")['default']
    'LazyIconVsfFull': typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsfFull.vue")['default']
    'LazyAppEdit': typeof import("../node_modules/sf-docs-base/components/app/AppEdit.vue")['default']
    'LazyAppFooter': typeof import("../node_modules/sf-docs-base/components/app/AppFooter.vue")['default']
    'LazyAppHeader': typeof import("../node_modules/sf-docs-base/components/app/AppHeader.vue")['default']
    'LazyAppLayout': typeof import("../node_modules/sf-docs-base/components/app/AppLayout.vue")['default']
    'LazyAppLayoutDefault': typeof import("../node_modules/sf-docs-base/components/app/AppLayoutDefault.vue")['default']
    'LazyAppLayoutFullscreen': typeof import("../node_modules/sf-docs-base/components/app/AppLayoutFullscreen.vue")['default']
    'LazyAppSearch': typeof import("../node_modules/sf-docs-base/components/app/AppSearch.vue")['default']
    'LazyAppSidebar': typeof import("../node_modules/sf-docs-base/components/app/AppSidebar.vue")['default']
    'LazyAppSidebarBottom': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarBottom.vue")['default']
    'LazyAppSidebarTop': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTop.vue")['default']
    'LazyAppSidebarTree': typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTree.vue")['default']
    'LazyAppTableOfContents': typeof import("../node_modules/sf-docs-base/components/app/AppTableOfContents.vue")['default']
    'LazyAppTag': typeof import("../node_modules/sf-docs-base/components/app/AppTag.vue")['default']
    'LazyAppVersionSelector': typeof import("../node_modules/sf-docs-base/components/app/AppVersionSelector.vue")['default']
    'LazyReferenceCode': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceCode.vue")['default']
    'LazyReferenceFunction': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceFunction.vue")['default']
    'LazyReferenceInterface': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceInterface.vue")['default']
    'LazyReferenceItem': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceItem.vue")['default']
    'LazyReferenceProperties': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperties.vue")['default']
    'LazyReferenceProperty': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperty.vue")['default']
    'LazyReferenceReferences': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceReferences.vue")['default']
    'LazyReferenceVariable': typeof import("../node_modules/sf-docs-base/components/reference/ReferenceVariable.vue")['default']
    'LazySfDropdown': typeof import("../node_modules/sf-docs-base/components/sf/SfDropdown.vue")['default']
    'LazyContentDoc': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'LazyMarkdown': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseCodeInline': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'LazyProsePre': typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseEm': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH5': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProseScript': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyMDC': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
    'LazyMDCRenderer': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
    'LazyMDCSlot': typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CodeEmbed: typeof import("../components/content/CodeEmbed.vue")['default']
export const Card: typeof import("../node_modules/sf-docs-base/components/content/Card.vue")['default']
export const CodeGroup: typeof import("../node_modules/sf-docs-base/components/content/CodeGroup.vue")['default']
export const Container: typeof import("../node_modules/sf-docs-base/components/content/Container.vue")['default']
export const Danger: typeof import("../node_modules/sf-docs-base/components/content/Danger.vue")['default']
export const DocsArrowLink: typeof import("../node_modules/sf-docs-base/components/content/DocsArrowLink.vue")['default']
export const DocsButton: typeof import("../node_modules/sf-docs-base/components/content/DocsButton.vue")['default']
export const Grid: typeof import("../node_modules/sf-docs-base/components/content/Grid.vue")['default']
export const Info: typeof import("../node_modules/sf-docs-base/components/content/Info.vue")['default']
export const IntegrationList: typeof import("../node_modules/sf-docs-base/components/content/IntegrationList.vue")['default']
export const List: typeof import("../node_modules/sf-docs-base/components/content/List.vue")['default']
export const Partial: typeof import("../node_modules/sf-docs-base/components/content/Partial.vue")['default']
export const ReadMore: typeof import("../node_modules/sf-docs-base/components/content/ReadMore.vue")['default']
export const ReferenceExample: typeof import("../node_modules/sf-docs-base/components/content/ReferenceExample.vue")['default']
export const ReferencePropertyHeading: typeof import("../node_modules/sf-docs-base/components/content/ReferencePropertyHeading.vue")['default']
export const ReferenceToggle: typeof import("../node_modules/sf-docs-base/components/content/ReferenceToggle.vue")['default']
export const RemoteCode: typeof import("../node_modules/sf-docs-base/components/content/RemoteCode.vue")['default']
export const Steps: typeof import("../node_modules/sf-docs-base/components/content/Steps.vue")['default']
export const Subheader: typeof import("../node_modules/sf-docs-base/components/content/Subheader.vue")['default']
export const SwaggerDocs: typeof import("../node_modules/sf-docs-base/components/content/SwaggerDocs.vue")['default']
export const Tabs: typeof import("../node_modules/sf-docs-base/components/content/Tabs.vue")['default']
export const Tip: typeof import("../node_modules/sf-docs-base/components/content/Tip.vue")['default']
export const Warning: typeof import("../node_modules/sf-docs-base/components/content/Warning.vue")['default']
export const ContainerGradient: typeof import("../node_modules/sf-docs-base/components/content/container/ContainerGradient.vue")['default']
export const ContainerTab: typeof import("../node_modules/sf-docs-base/components/content/container/ContainerTab.vue")['default']
export const ProseA: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseA.vue")['default']
export const ProseCode: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseCode.vue")['default']
export const ProseH2: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH4.vue")['default']
export const IconAlgolia: typeof import("../node_modules/sf-docs-base/components/global/icon/IconAlgolia.vue")['default']
export const IconAmplience: typeof import("../node_modules/sf-docs-base/components/global/icon/IconAmplience.vue")['default']
export const IconBazaarvoice: typeof import("../node_modules/sf-docs-base/components/global/icon/IconBazaarvoice.vue")['default']
export const IconBloomreach: typeof import("../node_modules/sf-docs-base/components/global/icon/IconBloomreach.vue")['default']
export const IconCheckout: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCheckout.vue")['default']
export const IconCommercetools: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCommercetools.vue")['default']
export const IconConstructor: typeof import("../node_modules/sf-docs-base/components/global/icon/IconConstructor.vue")['default']
export const IconContentstack: typeof import("../node_modules/sf-docs-base/components/global/icon/IconContentstack.vue")['default']
export const IconCoveo: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCoveo.vue")['default']
export const IconLexasCMS: typeof import("../node_modules/sf-docs-base/components/global/icon/IconLexasCMS.vue")['default']
export const IconMollie: typeof import("../node_modules/sf-docs-base/components/global/icon/IconMollie.vue")['default']
export const IconOdoo: typeof import("../node_modules/sf-docs-base/components/global/icon/IconOdoo.vue")['default']
export const IconPlentyMarkets: typeof import("../node_modules/sf-docs-base/components/global/icon/IconPlentyMarkets.vue")['default']
export const IconPrestashop: typeof import("../node_modules/sf-docs-base/components/global/icon/IconPrestashop.vue")['default']
export const IconSAP: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSAP.vue")['default']
export const IconSanity: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSanity.vue")['default']
export const IconSpree: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSpree.vue")['default']
export const IconStorefrontUi: typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUi.vue")['default']
export const IconStorefrontUiFull: typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUiFull.vue")['default']
export const IconSylius: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSylius.vue")['default']
export const IconVsf: typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsf.vue")['default']
export const IconVsfFull: typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsfFull.vue")['default']
export const AppEdit: typeof import("../node_modules/sf-docs-base/components/app/AppEdit.vue")['default']
export const AppFooter: typeof import("../node_modules/sf-docs-base/components/app/AppFooter.vue")['default']
export const AppHeader: typeof import("../node_modules/sf-docs-base/components/app/AppHeader.vue")['default']
export const AppLayout: typeof import("../node_modules/sf-docs-base/components/app/AppLayout.vue")['default']
export const AppLayoutDefault: typeof import("../node_modules/sf-docs-base/components/app/AppLayoutDefault.vue")['default']
export const AppLayoutFullscreen: typeof import("../node_modules/sf-docs-base/components/app/AppLayoutFullscreen.vue")['default']
export const AppSearch: typeof import("../node_modules/sf-docs-base/components/app/AppSearch.vue")['default']
export const AppSidebar: typeof import("../node_modules/sf-docs-base/components/app/AppSidebar.vue")['default']
export const AppSidebarBottom: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarBottom.vue")['default']
export const AppSidebarTop: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTop.vue")['default']
export const AppSidebarTree: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTree.vue")['default']
export const AppTableOfContents: typeof import("../node_modules/sf-docs-base/components/app/AppTableOfContents.vue")['default']
export const AppTag: typeof import("../node_modules/sf-docs-base/components/app/AppTag.vue")['default']
export const AppVersionSelector: typeof import("../node_modules/sf-docs-base/components/app/AppVersionSelector.vue")['default']
export const ReferenceCode: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceCode.vue")['default']
export const ReferenceFunction: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceFunction.vue")['default']
export const ReferenceInterface: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceInterface.vue")['default']
export const ReferenceItem: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceItem.vue")['default']
export const ReferenceProperties: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperties.vue")['default']
export const ReferenceProperty: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperty.vue")['default']
export const ReferenceReferences: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceReferences.vue")['default']
export const ReferenceVariable: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceVariable.vue")['default']
export const SfDropdown: typeof import("../node_modules/sf-docs-base/components/sf/SfDropdown.vue")['default']
export const ContentDoc: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const Markdown: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProsePre: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseEm: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH5: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const MDC: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
export const MDCRenderer: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
export const MDCSlot: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCodeEmbed: typeof import("../components/content/CodeEmbed.vue")['default']
export const LazyCard: typeof import("../node_modules/sf-docs-base/components/content/Card.vue")['default']
export const LazyCodeGroup: typeof import("../node_modules/sf-docs-base/components/content/CodeGroup.vue")['default']
export const LazyContainer: typeof import("../node_modules/sf-docs-base/components/content/Container.vue")['default']
export const LazyDanger: typeof import("../node_modules/sf-docs-base/components/content/Danger.vue")['default']
export const LazyDocsArrowLink: typeof import("../node_modules/sf-docs-base/components/content/DocsArrowLink.vue")['default']
export const LazyDocsButton: typeof import("../node_modules/sf-docs-base/components/content/DocsButton.vue")['default']
export const LazyGrid: typeof import("../node_modules/sf-docs-base/components/content/Grid.vue")['default']
export const LazyInfo: typeof import("../node_modules/sf-docs-base/components/content/Info.vue")['default']
export const LazyIntegrationList: typeof import("../node_modules/sf-docs-base/components/content/IntegrationList.vue")['default']
export const LazyList: typeof import("../node_modules/sf-docs-base/components/content/List.vue")['default']
export const LazyPartial: typeof import("../node_modules/sf-docs-base/components/content/Partial.vue")['default']
export const LazyReadMore: typeof import("../node_modules/sf-docs-base/components/content/ReadMore.vue")['default']
export const LazyReferenceExample: typeof import("../node_modules/sf-docs-base/components/content/ReferenceExample.vue")['default']
export const LazyReferencePropertyHeading: typeof import("../node_modules/sf-docs-base/components/content/ReferencePropertyHeading.vue")['default']
export const LazyReferenceToggle: typeof import("../node_modules/sf-docs-base/components/content/ReferenceToggle.vue")['default']
export const LazyRemoteCode: typeof import("../node_modules/sf-docs-base/components/content/RemoteCode.vue")['default']
export const LazySteps: typeof import("../node_modules/sf-docs-base/components/content/Steps.vue")['default']
export const LazySubheader: typeof import("../node_modules/sf-docs-base/components/content/Subheader.vue")['default']
export const LazySwaggerDocs: typeof import("../node_modules/sf-docs-base/components/content/SwaggerDocs.vue")['default']
export const LazyTabs: typeof import("../node_modules/sf-docs-base/components/content/Tabs.vue")['default']
export const LazyTip: typeof import("../node_modules/sf-docs-base/components/content/Tip.vue")['default']
export const LazyWarning: typeof import("../node_modules/sf-docs-base/components/content/Warning.vue")['default']
export const LazyContainerGradient: typeof import("../node_modules/sf-docs-base/components/content/container/ContainerGradient.vue")['default']
export const LazyContainerTab: typeof import("../node_modules/sf-docs-base/components/content/container/ContainerTab.vue")['default']
export const LazyProseA: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseA.vue")['default']
export const LazyProseCode: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseCode.vue")['default']
export const LazyProseH2: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/sf-docs-base/components/content/prose/ProseH4.vue")['default']
export const LazyIconAlgolia: typeof import("../node_modules/sf-docs-base/components/global/icon/IconAlgolia.vue")['default']
export const LazyIconAmplience: typeof import("../node_modules/sf-docs-base/components/global/icon/IconAmplience.vue")['default']
export const LazyIconBazaarvoice: typeof import("../node_modules/sf-docs-base/components/global/icon/IconBazaarvoice.vue")['default']
export const LazyIconBloomreach: typeof import("../node_modules/sf-docs-base/components/global/icon/IconBloomreach.vue")['default']
export const LazyIconCheckout: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCheckout.vue")['default']
export const LazyIconCommercetools: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCommercetools.vue")['default']
export const LazyIconConstructor: typeof import("../node_modules/sf-docs-base/components/global/icon/IconConstructor.vue")['default']
export const LazyIconContentstack: typeof import("../node_modules/sf-docs-base/components/global/icon/IconContentstack.vue")['default']
export const LazyIconCoveo: typeof import("../node_modules/sf-docs-base/components/global/icon/IconCoveo.vue")['default']
export const LazyIconLexasCMS: typeof import("../node_modules/sf-docs-base/components/global/icon/IconLexasCMS.vue")['default']
export const LazyIconMollie: typeof import("../node_modules/sf-docs-base/components/global/icon/IconMollie.vue")['default']
export const LazyIconOdoo: typeof import("../node_modules/sf-docs-base/components/global/icon/IconOdoo.vue")['default']
export const LazyIconPlentyMarkets: typeof import("../node_modules/sf-docs-base/components/global/icon/IconPlentyMarkets.vue")['default']
export const LazyIconPrestashop: typeof import("../node_modules/sf-docs-base/components/global/icon/IconPrestashop.vue")['default']
export const LazyIconSAP: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSAP.vue")['default']
export const LazyIconSanity: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSanity.vue")['default']
export const LazyIconSpree: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSpree.vue")['default']
export const LazyIconStorefrontUi: typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUi.vue")['default']
export const LazyIconStorefrontUiFull: typeof import("../node_modules/sf-docs-base/components/global/icon/IconStorefrontUiFull.vue")['default']
export const LazyIconSylius: typeof import("../node_modules/sf-docs-base/components/global/icon/IconSylius.vue")['default']
export const LazyIconVsf: typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsf.vue")['default']
export const LazyIconVsfFull: typeof import("../node_modules/sf-docs-base/components/global/icon/IconVsfFull.vue")['default']
export const LazyAppEdit: typeof import("../node_modules/sf-docs-base/components/app/AppEdit.vue")['default']
export const LazyAppFooter: typeof import("../node_modules/sf-docs-base/components/app/AppFooter.vue")['default']
export const LazyAppHeader: typeof import("../node_modules/sf-docs-base/components/app/AppHeader.vue")['default']
export const LazyAppLayout: typeof import("../node_modules/sf-docs-base/components/app/AppLayout.vue")['default']
export const LazyAppLayoutDefault: typeof import("../node_modules/sf-docs-base/components/app/AppLayoutDefault.vue")['default']
export const LazyAppLayoutFullscreen: typeof import("../node_modules/sf-docs-base/components/app/AppLayoutFullscreen.vue")['default']
export const LazyAppSearch: typeof import("../node_modules/sf-docs-base/components/app/AppSearch.vue")['default']
export const LazyAppSidebar: typeof import("../node_modules/sf-docs-base/components/app/AppSidebar.vue")['default']
export const LazyAppSidebarBottom: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarBottom.vue")['default']
export const LazyAppSidebarTop: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTop.vue")['default']
export const LazyAppSidebarTree: typeof import("../node_modules/sf-docs-base/components/app/AppSidebarTree.vue")['default']
export const LazyAppTableOfContents: typeof import("../node_modules/sf-docs-base/components/app/AppTableOfContents.vue")['default']
export const LazyAppTag: typeof import("../node_modules/sf-docs-base/components/app/AppTag.vue")['default']
export const LazyAppVersionSelector: typeof import("../node_modules/sf-docs-base/components/app/AppVersionSelector.vue")['default']
export const LazyReferenceCode: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceCode.vue")['default']
export const LazyReferenceFunction: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceFunction.vue")['default']
export const LazyReferenceInterface: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceInterface.vue")['default']
export const LazyReferenceItem: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceItem.vue")['default']
export const LazyReferenceProperties: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperties.vue")['default']
export const LazyReferenceProperty: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceProperty.vue")['default']
export const LazyReferenceReferences: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceReferences.vue")['default']
export const LazyReferenceVariable: typeof import("../node_modules/sf-docs-base/components/reference/ReferenceVariable.vue")['default']
export const LazySfDropdown: typeof import("../node_modules/sf-docs-base/components/sf/SfDropdown.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const LazyMarkdown: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProsePre: typeof import("../node_modules/sf-docs-base/node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseEm: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH5: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProseScript: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyMDC: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
export const LazyMDCRenderer: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
export const LazyMDCSlot: typeof import("../node_modules/sf-docs-base/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
